# Generated by Django 2.2.28 on 2023-12-08 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231208_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('lessons_count', models.IntegerField(default=-1, verbose_name='Количество занятий')),
                ('full_course_price', models.FloatField(default=-1, verbose_name='Цена за весь курс со скидкой')),
                ('start_date', models.TextField(blank=True, verbose_name='Дата начала курса')),
                ('fdate_date', models.TextField(blank=True, verbose_name='Дата окончания курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'Courses',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='full_course_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_course',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lessons_count',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 18, 51, 23, 452839), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 18, 51, 23, 452839), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 18, 51, 23, 455819), verbose_name='Дата создания'),
        ),
    ]
