# Generated by Django 2.2.28 on 2023-12-10 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20231210_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='data',
            field=models.TextField(default='{}', verbose_name='Данные корзины'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 10, 17, 7, 36, 753624), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 10, 17, 7, 36, 753624), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 10, 17, 7, 36, 758613), verbose_name='Дата создания'),
        ),
    ]
